### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by genjikowa** [pelledrijver/highlights-bot#3]
Help me configure this software seems very interesting

**Comment by pelledrijver** [comment]
Sorry for the late response! I'm currently working behind the scenes on packaging the project and making it easier to configure. I will notify you once I've finished doing so!

**Comment by genjikowa** [comment]
Wow thank you very much for answering !! I hope it is soon I really want to try it!

**Comment by pelledrijver** [comment]
Hi @genjikowa, I finally finished packaging the project and importing the module should be very straightforward now. The README.md now contains clear instructions on how to get started :)

**Comment by genjikowa** [comment]
Hi, great that you have updated the program. Do you have discord so we can talk about new features?
