### ISSUE TITLE
Can u help me?

### ISSUE THREAD

**Issue by genjikowa** [pelledrijver/highlights-bot#4]
Hi, great that you have updated the program. 

I wrote to you in the other section but you closed it and I don't think you have received the notification.

The IMPORT command (gives me an error)

Do you have discord so we can talk about new features and help me how to make it run on windows??

Thanks!

**Comment by pelledrijver** [comment]
Hi Genji, I don't have a dedicated server yet, but you can add me on Pelle#6238. I believe you used the import statement in the shell rather than the Python script, but let's discuss it on Discord to resolve the issue

**Comment by pelledrijver** [comment]
Also, I will try to create a folder with working example code in this repository by the end of next week!

**Comment by genjikowa** [comment]
I have already sent you a request on discord
