### ISSUE TITLE
Make video by category language doesn't work

### ISSUE THREAD

**Issue by Phaired** [pelledrijver/highlights-bot#6]
The language when I want to make video in French does't seems to work
`highlight_generator = TwitchHighlights()
twitch_credentials = {
   "client_id": "xxx",
   "client_secret": "xxx"
}
highlight_generator.login_twitch(twitch_credentials)

highlight_generator.make_video_by_category(category = "Minecraft", language = "fr", video_length = 1)`

**Comment by pelledrijver** [comment]
Hi @Phaired,
Thank you for notifying me about this bug! I immediately checked running your code and the code indeed does not work as expected. I had a quick glance at the code and spotted the error. A filtered list containing clips of a certain language is obtained, but I keep using the unfiltered original list. I patched the bug locally and the language filtering should work after the next release is published (will probably happen by the end of this week).
~Pelle

**Comment by pelledrijver** [comment]
The language filtering feature should work as expected now in the new release (v1.1.0)
